services:
  plantuml:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    ports:
      - "8080:8080"
    volumes:
      - plantuml_data:/app/data
    restart: unless-stopped

volumes:
  plantuml_data:
    driver: local
